version: "3.2"
services:
    app_dev:
        shm_size: 40G
        volumes:
            - ${PWD}:/workspace/
        working_dir: /workspace
        environment:
            WANDB_API_KEY: $WANDB_API_KEY

    app_prod:
        extends:
            service: app_dev
        volumes:
            - /media/gengar/:/media/gengar/
        devices:
            - /dev/nvidia0
        environment:
            NVIDIA_VISIBLE_DEVICES: 0
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
